javac -classpath ../classes:. eg1.java
javac -classpath ../classes:. eg2.java
javac -classpath ../classes:. eg3.java
javac -classpath ../classes:. eg4.java
javac -classpath ../classes:. eg5.java
javac -classpath ../classes:. eg6.java
javac -classpath ../classes:. eg7.java
javac -classpath ../classes:. eg8.java
javac -classpath ../dist/tmcommon.jar:. TestGeneric.java
javac -classpath ../dist/*:. TestGeneric.java
#java -classpath ../dist/*:. TestGeneric
#java -classpath ../dist/tmcommon.jar:. TestGeneric
#java -classpath ../classes:. psp
