insert into Member (uname,pwd) values("Ayush salve","ayush");
insert into Member (uname,pwd) values("Ayush S.","ayush");
insert into Member (uname,pwd) values("Rajendra","rajendra");
insert into Member (uname,pwd) values("Ramesh","ramesh");
insert into Member (uname,pwd) values("Sumit","sumit");
insert into Member (uname,pwd) values("Kiran","kiran");
insert into Member (uname,pwd) values("Shrestha","shrestha");
insert into Member (uname,pwd) values("Rohit","rohit");
insert into Member (uname,pwd) values("Shidarth","shidarth");
insert into Member (uname,pwd) values("Ankit","ankit");
insert into Member (uname,pwd) values("Suman","suman");
insert into Member (uname,pwd) values("Rahu","rahu");
insert into Member (uname,pwd) values("Ketu","ketu");
insert into Member (uname,pwd) values("Kittu","kittu");
insert into Member (uname,pwd) values("Roy","roy");
insert into Member (uname,pwd) values("Don","don");
insert into Member (uname,pwd) values("Bala","bala");
insert into Member (uname,pwd) values("Sunny","sunny");
insert into Member (uname,pwd) values("Munny","munny");
insert into Member (uname,pwd) values("Honey","honey");
insert into Member (uname,pwd) values("Tanu","tanu");
insert into Member (uname,pwd) values("Priyal","priyal");
